### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/capstone-project#167]
I'm trying to add a hover effect to my images but I'm not sure where to insert this HTML so that it works. I'm loading my images via a JS file.

Here's the HTML I need to insert:

``` html
      <div class="hovereffect">
          <img class="img-responsive" src="http://placehold.it/316x195" alt="">
              <div class="overlay">
                  <h2>Hover effect 7</h2>
                  <p>
                      <a href="#">
                          <i class="fa fa-twitter"></i>
                      </a>
                      <a href="#">
                          <i class="fa fa-facebook"></i>
                      </a>
                      <a href="#">
                          <i class="fa fa-instagram"></i>
                      </a>
                      <a href="#">
                          <i class="fa fa-dribbble"></i>
                      </a>
                  </p>
              </div>
      </div>
```

Here's where I'm referencing the JS in my HTML:

``` html
<div class="jribble-content">
  <ul class="shots"></ul>

    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/jribbble/dist/jribbble.min.js"></script>
    <script src="assets/scripts/jribbble.js"></script>
</div>
```

Here's my JS file:

``` js
'use strict'

$.jribbble.setToken('829e7b01d4f7bf4fae734bf7af259e228706a7f08abb66459fad663ed89e68db');
$.jribbble.shots({per_page: 100}).then(function(shots) {
  var html = [];

//for each shot on the page, give it a link and an image
  shots.forEach(function(shot) {
    html.push('<div class="shots--shot" data-id="' + shot.id + '">');
    html.push('<a href="' + shot.html_url + '" target="_blank">');
    html.push('<img src="' + shot.images.normal + '">');
    html.push('</a></div>');
  });

  $('.shots').html(html.join(''));
});
```

**Comment by laurenfazah** [comment]
Is the hover effect itself coming from CSS? If so, remember that the HTML for your image cards is built through those lines of JS. You likely have to change the HTML you're pushing to either add the correct class, or add the bits of info that appear on hover there.

**Comment by Jcornmanhomonoff** [comment]
Yes it is but I also have to add certain HTML pieces to it. I'm having difficulty placing the effect on each individual image and I've tried adding the classes via the JS doc.

**Comment by laurenfazah** [comment]
Could I see the CSS for the hover effect? And the JS with the classes added?

**Comment by gaand** [comment]
Are you using the js-template?

**Comment by Jcornmanhomonoff** [comment]
``` scss
.hovereffect {
  width: 100%;
  height: 100%;
  float: left;
  overflow: hidden;
  position: relative;
  text-align: center;
  cursor: default;
}

.hovereffect .overlay {
  width: 100%;
  height: 100%;
  position: absolute;
  overflow: hidden;
  top: 0;
  left: 0;
}

.hovereffect img {
  display: block;
  position: relative;
}

.hovereffect h2 {
  text-transform: uppercase;
  color: #fff;
  text-align: center;
  font-size: 17px;
}

.hovereffect:hover h2 {
  opacity: 0;
  filter: alpha(opacity=0);
  -webkit-transform: translate3d(-50%,-50%,0) scale3d(0.8,0.8,1);
  transform: translate3d(-50%,-50%,0) scale3d(0.8,0.8,1);
}

.hovereffect a.info {
  display: inline-block;
  text-decoration: none;
  padding: 7px 14px;
  text-transform: uppercase;
  color: #fff;
  border: 1px solid #fff;
  margin: 50px 0 0 0;
  background-color: transparent;
}

.hovereffect a.info:hover {
  box-shadow: 0 0 5px #fff;
}

.hovereffect h2,
.hovereffect p {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
  transition: opacity 0.35s, transform 0.35s;
  -webkit-transform: translate3d(-50%,-50%,0);
  transform: translate3d(-50%,-50%,0);
  -webkit-transform-origin: 50%;
  -ms-transform-origin: 50%;
  transform-origin: 50%;
  background-color: transparent;
  margin: 0px;
  padding: 0px;
}

.hovereffect .overlay:before {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 40%;
  height: 60%;
  border: 2px solid #fff;
  content: '';
  opacity: 0;
  filter: alpha(opacity=0);
  -webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
  transition: opacity 0.35s, transform 0.35s;
  -webkit-transform: translate3d(-50%,-50%,0) rotate3d(0,0,1,-45deg) scale3d(0,0,1);
  transform: translate3d(-50%,-50%,0) rotate3d(0,0,1,-45deg) scale3d(0,0,1);
  -webkit-transform-origin: 50%;
  -ms-transform-origin: 50%;
  transform-origin: 50%;
}

.hovereffect p {
  width: 20%;
  text-transform: none;
  font-size: 15px;
  line-height: 2;
}

.hovereffect p a {
  color: #fff;
}

.hovereffect p a:hover,
.hovereffect p a:focus {
  opacity: 0.6;
  filter: alpha(opacity=60);
}

.hovereffect  a i {
  opacity: 0;
  filter: alpha(opacity=0);
  -webkit-transition: opacity 0.35s, -webkit-transform 0.35s;
  transition: opacity 0.35s, transform 0.35s;
  padding: 0px 5px;
}

.hovereffect p a:first-child i {
  -webkit-transform: translate3d(-60px,-60px,0);
  transform: translate3d(-60px,-60px,0);
}

.hovereffect p a:nth-child(2) i {
  -webkit-transform: translate3d(60px,-60px,0);
  transform: translate3d(60px,-60px,0);
}

.hovereffect p a:nth-child(3) i {
  -webkit-transform: translate3d(-60px,60px,0);
  transform: translate3d(-60px,60px,0);
}

.hovereffect p a:nth-child(4) i {
  -webkit-transform: translate3d(60px,60px,0);
  transform: translate3d(60px,60px,0);
}

.hovereffect:hover .overlay:before {
  opacity: 1;
  filter: alpha(opacity=100);
  background-color: rgba(0,0,0,0.2);
  -webkit-transform: translate3d(-50%,-50%,0) rotate3d(0,0,1,-135deg) scale3d(1,1,1);
  transform: translate3d(-50%,-50%,0) rotate3d(0,0,1,-135deg) scale3d(1,1,1);
}

.hovereffect:hover p i:empty {
  -webkit-transform: translate3d(0,0,0);
  transform: translate3d(0,0,0);
  opacity: 1;
  filter: alpha(opacity=100);
}
```

``` js
'use strict'

$.jribbble.setToken('829e7b01d4f7bf4fae734bf7af259e228706a7f08abb66459fad663ed89e68db');
$.jribbble.shots({per_page: 100}).then(function(shots) {
  var html = [];

//for each shot on the page, give it a link and an image
  shots.forEach(function(shot) {
    html.push('<div class="shots--shot overlay" data-id="' + shot.id + '">');
    html.push('<a href="' + shot.html_url + '" target="_blank">');
    html.push('<img src="' + shot.images.normal + '">');
    // html.push('<i class="fa fa-twitter fa-facebook fa-instagram fa-dribbble">')
    html.push('</a></div>');
  });

  $('.shots').html(html.join(''));
});

//get id of image
$('.shots--shot').on('click', function(){
    $(this).data('id');
});
```
