### ISSUE TITLE
Nested components

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/capstone-project#306]
I'm working on the components in Ember.

I want to make a search-box component.

Inside, I want the following components:

search-header,
search-field,
search-results

I thought the way to do this was ```ember generate search-box/search-header```, etc. so that is what I did. 

However, I am not sure if I did it correctly. None of the nested elements render. 

For example, in ```search-box/search-header``` I have this:

```html
<div class="search-header">
</div>
```

and the class is set in the scss file with this:

```css
.search-header {
  border: 1px solid $black;
  height: 10px;
  width: 100%;
}
```

And yet nothing shows up on the page. What am I doing wrong?
