### ISSUE TITLE
automatically scroll to bottom of <div>?

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#447]
I have a <div> that will be filled dynamically with text content. I want to ensure that the div remains scrolled to the bottom, should the content go beyond the height of the div, and I cant think of an easy way to do it. Here's my code:

template for the riff components, which will fill the div:
```js
{{#if isDisplayed}}
  {{#link-to 'riff' riff}}

{{#if isUser}}
  <span class="user-riff">{{riff.user.email}}</span>:
{{else}}
  {{riff.user.email}}:
{{/if}}
  {{riff.text}}
  <span class="riff-stamp">-- @{{stampTime}}</span>{{/link-to}}
{{/if}}
```

code for the component file:

```js
import Ember from 'ember';

export default Ember.Component.extend({
  auth: Ember.inject.service(),
  user: Ember.computed.alias('auth.credentials.email'),

  isUser: Ember.computed('user', 'riff.user.email', function() {
    return this.get('riff.user.email') === this.get('user');
  }),

  currentTime: 0,
  stampTime: Ember.computed('stamp', function() {
    let d = Number(this.get('riff.stamp'));
    let h = Math.floor(d / 3600);
    let m = Math.floor(d % 3600 / 60);
    let s = Math.floor(d % 3600 % 60);

    let hDisplay = h > 0 ? h + (h === 1 ? ":" : ":") : "";
    let mDisplay = m > 0 ? m + (m === 1 ? ":" : ":") : "";
    let sDisplay = s > 0 ? s + (s === 1 ? ":" : "") : "";
    return hDisplay + mDisplay + sDisplay;
  }),

  isDisplayed: Ember.computed('currentTime', 'stamp', function() {
    return this.get('riff').get('stamp') < this.get('currentTime');
  }),
});
```

The div is also styled to be scrollable:

```css
.chat-box {
  -moz-appearance: textfield-multiline;
  -webkit-appearance: textarea;
  border: 1px solid $grey;
  height: 325px;
  overflow: auto;
  padding: 2px;
  resize: both;
  width: 100%;

  @media (max-width: 992px) {
    width: 640px;
  };
}
```
