### ISSUE TITLE
Cannot get fonts to load

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#701]
I've tried the following in app/index.js
```js
<head>
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
</head>
```
but the font doesn't get accessed by app.scss with code such as the following:
```css
body {
  font-family: 'Sans Source Pro', sans-serif;
}
```
There's something opaque going on that I can't figure out.
