### ISSUE TITLE
Bootstrap CSS not honoring padding around borders?

### ISSUE THREAD

**Issue by EricLScace** [ga-wdi-boston/capstone-project#724]
Objective 1: add some distance between the top of a container (shown by the dotted outline) and the first line of text.

Objective 2: reduce/control the space between the left side of the text and the border.

One would think that padding handles this. It does not. Forcing padding values does not achieve the objectives. Furthermore, adding padding to the top actually places the spacing outside the border. WTF?

Thoughts?
<img width="1012" alt="screen shot 2017-07-18 at 10 05 38" src="https://user-images.githubusercontent.com/6785602/28321229-b6ec3802-6ba0-11e7-805e-02f3a59e0f65.png">
 ```css

body {
  background-color: $gray;
  box-sizing: border-box;
  font-family: $font-family;
  font-size: $font-size;
  font-style: $font-style;
  font-weight: $font-weight;
  line-height: $line-height;
  // Must override the .container-fluid values for left & right padding
  margin-left: 0 !important;
  padding-left: 0 !important;
  padding-right: 0 !important;
  padding-top: 10;

}
```

**Comment by jordanallain** [comment]
are you only adding style rules to the body?

**Comment by EricLScace** [comment]
row-0.hbs file lays out the row (for now, pre-componentizing...)

```css
{{!-- Place everything in one row --}}
<div class="container-fluid">
  {{!-- Top of display --}}

  {{!-- Top-left corner: choose type of search --}}
  {{!-- Fixed-width container --}}
  <div class="input-box container col-sm-2 height-row-0">
    Search selector goes here
  </div>

  {{!-- Fixed-width container: matrix image--}}
  <div class="test-box container col-sm-2 height-row-0">
    Matrix image goes here
  </div>

  {{!-- Fixed-width container: app title --}}
  <div class="test-box app-title container col-sm-4 height-row-0">
    All the Matrices
  </div>

  {{!-- Fixed-width container: logged-in user description --}}
  <div class="test-box container col-sm-2 height-row-0">
    Logged in user name & organization
  </div>

  {{!-- Top-right corner: authentication actions --}}
  <div class="test-box container col-sm-2 height-row-0">
    Authentication actions
  </div>
</div>
```

**Comment by EricLScace** [comment]
class styles controlled here:
```css
@import './colors';
@import './shapes';
@import './typography';

// Classes are for styling.
// IDs are for UX behavior.

body {
  background-color: $gray;
  box-sizing: border-box;
  font-family: $font-family;
  font-size: $font-size;
  font-style: $font-style;
  font-weight: $font-weight;
  line-height: $line-height;
  // Must override the .container-fluid values for left & right padding
  margin-left: 0 !important;
  padding-left: 0 !important;
  padding-right: 0 !important;
  padding-top: 10;

}

.app-title {
  font-size: $font-size-title;
  text-align: center;
}

.height-row-0 {
  min-height: $min-height-row-0;
}

.input-box {
  background-color: $white;
  border-radius: $border-radius;
  box-shadow: $box-shadow;
  min-height: $min-height-row-0;
}

.test-box {
  border: $border-test;
  border-radius: $border-radius;
}
```
